parameters:
- name: REPO_NAME
  type: string
- name: IGNORE_STYLE
  type: boolean
  default: false
- name: COMPLEX
  type: boolean
  default: false
- name: GCC_CONFIG
  type: string
- name: INTEL_CONFIG
  type: string
- name: BUILD_REAL
  type: string
  default: .github/build_real.sh
- name: TEST_REAL
  type: string
  default: .github/test_real.sh
- name: BUILD_COMPLEX
  type: string
  default: .github/build_complex.sh
- name: TEST_COMPLEX
  type: string
  default: .github/test_complex.sh

stages:
- stage:
  dependsOn: []
  displayName: Test Real
  jobs:
  - template: azure_build.yaml
    parameters:
      REPO_NAME: ${{ parameters.REPO_NAME }}
      GCC_CONFIG: ${{ parameters.GCC_CONFIG }}
      INTEL_CONFIG: ${{ parameters.INTEL_CONFIG }}
      BUILD: ${{ parameters.BUILD_REAL }}
      TEST: ${{ parameters.TEST_REAL }}

- stage:
  dependsOn: []
  displayName: Test Complex
  condition: eq(${{ parameters.COMPLEX }}, true)
  jobs:
  - template: azure_build.yaml
    parameters:
      REPO_NAME: ${{ parameters.REPO_NAME }}
      GCC_CONFIG: ${{ parameters.GCC_CONFIG }}
      INTEL_CONFIG: ${{ parameters.INTEL_CONFIG }}
      BUILD: ${{ parameters.BUILD_COMPLEX }}
      TEST: ${{ parameters.TEST_COMPLEX }}

- stage:
  dependsOn: []
  displayName: Style
  jobs:
  - template: azure_style.yaml
    parameters:
      REPO_NAME: ${{ parameters.REPO_NAME }}
      IGNORE_STYLE: ${{ parameters.IGNORE_STYLE }}