parameters:
- name: REPO_NAME
  type: string
- name: IGNORE_STYLE
  type: boolean
  default: false
- name: COMPLEX
  type: boolean
  default: false
- name: GCC_CONFIG
  type: string
  default: empty
- name: INTEL_CONFIG
  type: string
  default: empty
- name: BUILD_REAL
  type: string
  default: .github/build_real.sh
- name: TEST_REAL
  type: string
  default: .github/test_real.sh
- name: BUILD_COMPLEX
  type: string
  default: .github/build_complex.sh
- name: TEST_COMPLEX
  type: string
  default: .github/test_complex.sh
- name: PRIVATE
  type: boolean
  default: false
- name: PYPI
  type: boolean
  default: false

stages:
- stage: Test_Real
  dependsOn: []
  displayName: Test Real
  jobs:
  - template: azure_build.yaml
    parameters:
      REPO_NAME: ${{ parameters.REPO_NAME }}
      GCC_CONFIG: ${{ parameters.GCC_CONFIG }}
      INTEL_CONFIG: ${{ parameters.INTEL_CONFIG }}
      BUILD: ${{ parameters.BUILD_REAL }}
      TEST: ${{ parameters.TEST_REAL }}
      PRIVATE: ${{ parameters.PRIVATE }}

- stage: Test_Complex
  dependsOn: []
  displayName: Test Complex
  condition: eq(${{ parameters.COMPLEX }}, true)
  jobs:
  - template: azure_build.yaml
    parameters:
      REPO_NAME: ${{ parameters.REPO_NAME }}
      GCC_CONFIG: ${{ parameters.GCC_CONFIG }}
      INTEL_CONFIG: ${{ parameters.INTEL_CONFIG }}
      BUILD: ${{ parameters.BUILD_COMPLEX }}
      TEST: ${{ parameters.TEST_COMPLEX }}
      PRIVATE: ${{ parameters.PRIVATE }}

- stage: Style
  dependsOn: []
  displayName: Style
  jobs:
  - template: azure_style.yaml
    parameters:
      REPO_NAME: ${{ parameters.REPO_NAME }}
      IGNORE_STYLE: ${{ parameters.IGNORE_STYLE }}

- stage:
  dependsOn:
  - Test_Real
  # - Test_Complex address at later date (if needed)
  - Style
  displayName: PyPI
  condition: and(succeeded(), eq(${{ parameters.PYPI }}, true), contains(variables['build.sourceBranch'], 'tags'))
  jobs:
  - job:
    steps:
    - script: echo ${{ variables['Build.Reason'] }}